### ISSUE TITLE
Instructions on structuring documents?

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#1]
Our info here says we provide "and instructions for exactly how to structure the documents" (the papers being prepared for submission). Seems like it should have a link. Do we have this info? Where is it?

**Comment by mrshirts** [comment]
Yep, we need to start adding suggestions.  Perhaps should go in the templates area?

**Comment by davidlmobley** [comment]
I'm thinking maybe we want to just try and put most everything informational on the website and only put things people will USE in the repos. Otherwise I'm worried we're going to end up with too many things in too many places so you have to be an expert to figure out where anything is. Maybe we can make the website clearly indicate exactly where to find everything.

**Comment by davidlmobley** [comment]
Closed by #102
