### ISSUE TITLE
Links not (sufficiently) visible

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#101]
It looks like links are not currently visible enough (or visible at all?) on livecomsjournal.github.io; @ptmerz is there an easy way to make these more contrasting? 

See attached screenshot of the main instructions for authors page, which has a link to the templates page. The link is invisible but active. 
![links](https://user-images.githubusercontent.com/7132257/33184122-e5ddfeea-d02f-11e7-9697-8c1cbbde9ca1.jpg)

**Comment by ptmerz** [comment]
PR #111 should solve that. This will color the links in https://livecomsjournal.github.io/authors/ (and all other pages using the same layout) in the same blue as in other pages (see e.g. https://livecomsjournal.github.io/authors/policies/). I prevented the titles below (General Author Instructions, Best Practices Guides, Perpetual Reviews, Comparisons of Molecular Simulation Packages, Tutorials, Lessons Learned) to be colored, even though they are also links, feeling that the page looks too blue if you do. I can change that if you think these links should be more visible too, though.

**Comment by davidlmobley** [comment]
Looks much better now, thanks!
