### ISSUE TITLE
Linking contributor license on the webpage?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#164]
We need to link the contributor license to the author instructions.  Right now, it doesn't appear to actually be linked anywhere.  But I'm not sure how to link it with the MarkDown setup.  Any suggestion?  I could link directly to the GitHub, but it seems like there should be some direct link.

On GitHub, its at:
https://github.com/livecomsjournal/livecomsjournal.github.io/blob/master/_author_instructions/LiveCoMS_contributor_license.pdf

**Comment by dmzuckerman** [comment]
One comment on the form itself.  Do we really want faxes or regular mails?  Seems like we should require email or upload if that's possible.

And I'm not clear why you can't make a regular link with markdown ... won't that just download the pdf??

**Comment by mrshirts** [comment]
I will fix it so that email is preferred.  

And I'm not clear why you can't make a regular link with markdown ... won't that just download the pdf?? 

The problem is that the paths get changed by jekyll.  Not sure how.

**Comment by dmzuckerman** [comment]
Ask Melanie?

**Comment by mrshirts** [comment]
I was hoping @archgirl would see the post here :)

**Comment by archgirl** [comment]
We should be able to create an assets/pdf folder and then use a direct link to https://livecomsjournal.github.io/assets/pdf/LiveCoMS_contributor_license.pdf as a valid link without all the extra /blob/ stuff.

Shall I run a local test? :D

**Comment by mrshirts** [comment]
Works for me!

**Comment by archgirl** [comment]
Great news! It seems to be working like a charm. [Here's a quick Loom](https://www.useloom.com/share/e3b2f4cfdb824d1fbe8c934801d11139) about how the change works, which I'm sticking on the PR notes as well!
