### ISSUE TITLE
Do we have a preferred format for dates

### ISSUE THREAD

**Issue by oostenbrink** [livecomsjournal/livecomsjournal.github.io#169]
In the instructions for editors, we write:
"Have the author enable the LiveCoMS footer by including the ‘pubversion’ class option in the document preamble, fill in the ‘\datereceived’ and ‘\dateaccepted’ fields, and provide a recompiled PDF for posting to the editor handling the submission and a managing editor."

Do we have a preferred format for how to write the date? 
dd-mm-yyyy
dd Month yyyy
Month dd yyyy
yyyymmdd

Can we include this in a comment in the template?

**Comment by dwsideriusNIST** [comment]
I'm in favor of an international convention; choose between short form and long forms:

ISO 8601:  YYYY-MM-DD   (also best for computer science applications, but is utilitarian)

Longform (no standard AFAIK): D mmmmm YYYY  (better aesthetically)

**Comment by davidlmobley** [comment]
Sounds good to me! Anyone want to volunteer to modify the template?

(I am OK with either short or long forms.)

**Comment by dwsideriusNIST** [comment]
I can modify the template, but you'll end up with my preference (longform, international format)

**Comment by oostenbrink** [comment]
I'd be happy with your suggested long form.

**Comment by dmzuckerman** [comment]
No objection from me.

**Comment by davidlmobley** [comment]
Fine by me too.

**Comment by dwsideriusNIST** [comment]
I submitted a PR in the article_templates repo to address this. I'll look in the author guidelines and determine if a PR is needed there as well.

**Comment by mrshirts** [comment]
Addressed with https://github.com/livecomsjournal/article_templates/pull/65
