### ISSUE TITLE
Resolve questions on index.md

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#2]
I have some questions on index.md, @mrshirts .

- Currently we have this info in the section on preparing documents for submission: "Questions, comments, or additions from the community would be filed as issues and then could be incorporated." I propose we remove it, as it seems to be out of place there (it seems like it should be (a) in the "paper writing as code development" document, and possibly (b) also in something else which gives more practical instructions for using GitHub). Maybe we can replace it with a link to "For information on using GitHub for paper-writing, see (link) for philosophical issues and (link) for practical tips."
- ~"Posting to the preprint server can be done at any time before review." What does this mean? Don't we want to say they should submit first and then upload their PDF for review? Or are we saying that they can post anytime they want as long as they post before we arrange for the paper to be reviewed? Do we mean, "Posting to the preprint server can be done at any time prior to submission." ??~ 
- ~Authors should first send a presubmission letter to the lead editor in the relevant area: This needs a link to a list of people with contact info. Where will we have that list?~

**Comment by davidlmobley** [comment]
I think I resolved the last of these by reading further. We mean, "Posting to the preprint server can be done at any time prior to submission."

**Comment by mrshirts** [comment]
> Authors should first send a presubmission letter to the lead editor in the relevant area: This needs a link to a list of people with contact info. Where will we have that list? 

We can link back to the Editorial board web page.  Thanks for the reminder, I will change that.

**Comment by mrshirts** [comment]
> Currently we have this info in the section on preparing documents for submission: "Questions, comments, or additions from the community would be filed as issues and then could be incorporated." 

Good question.  I think that the rationale for using Github is important to present upfront.  I'll look over and think of different ways to organize this.

**Comment by mrshirts** [comment]
I think I addressed the first comment in PR #7

**Comment by davidlmobley** [comment]
@mrshirts - I don't really have a problem with the idea of including that info about additions/use of GitHub, but it is out of place where it was originally, AND where it is now. This is info about how to involve the community in improving an article, so it doesn't belong with the rest of the material in "Updating LiveCoMS articles" which is more focused on how to update and rules concerning updating. 

Maybe you want to break it into a subsection under "Updating..." and call that subsection "Getting community involvement/support in improving articles" and say a little bit more about that, @mrshirts ?

**Comment by mrshirts** [comment]
OK, updated and created a link to "paper as code" document on the web page.

**Comment by davidlmobley** [comment]
Thanks. I think this is resolved now, with last details polished off by #19 .
