### ISSUE TITLE
"Lesson learned" article type

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#20]
So, sounds like from the workshop, we could use a fifth type of article: "Lessons learned", which contain compilations of lessons learned from what went WRONG on a given topic.  Perhaps Dan Zuckerman would like to write up a brief description (matching what we have for the requirements for the other types of articles) and serve as the lead editor for that article type?

**Comment by davidlmobley** [comment]
I think we got this resolved -- got some material merged in on this from Dan in #32 and #33 .
