### ISSUE TITLE
Front Page Links

### ISSUE THREAD

**Issue by whitead** [livecomsjournal/livecomsjournal.github.io#202]
the abstract buttons for me on the top two articles on the main page have null links for me. They point to `https://www.livecomsjournal.org/null`

Per Twitter via @jchodera 

![image](https://user-images.githubusercontent.com/908389/102929785-3cf6e380-4469-11eb-8e58-6f51e7fc045b.png)

**Comment by mrshirts** [comment]
Thanks so much for checking, Andrew!  Do you have a popup blocker on?
These links pop up the abstract (not necessarily ideal, but what the
publishing software sets it up as in a nonconfigurable way).

**Comment by whitead** [comment]
@mrshirts Yes, disabling my adblocker fixed it. Yeah I thought the abstract buttons were links, but I see now they open a pop-up with JS and the link is not meant to be followed. 

For reference, I was on Firefox `84.0.1 (64-bit)` with Adblock Plus. What's strange is that I cannot repeat the behavior when re-enabling my ad blocker, so I guess it's fixed now? Anyway, thanks for the quick response.
