### ISSUE TITLE
Link to style guide broken

### ISSUE THREAD

**Issue by ltalirz** [livecomsjournal/livecomsjournal.github.io#214]
The link https://pubs.acs.org/doi/pdf/10.1021/bk-2006-STYG.ch009 for guidelines on grammar, spelling, and punctuation in the [author instructions](https://github.com/livecomsjournal/livecomsjournal.github.io/blob/1ea2bb9e27e709c3f82573d0a3c75a7b4dca9ab2/_author_instructions/01_policies.md#writing-style-and-editing) is broken

![image](https://user-images.githubusercontent.com/1053245/134146588-57e2e918-160f-4080-9d28-42dff4df59c6.png)

**Comment by dwsideriusNIST** [comment]
Looks like ACS changed the document structure, so we need to re-cross-reference the sections

**Comment by davidlmobley** [comment]
I think ACS may have even moved it behind a paywall. :( I've had in my list that I need to make our own style guide; maybe it's time to prioritize that.
