### ISSUE TITLE
Develop a policy for how to handle dead documents

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#22]
What happens when the main author of a repository doesn't want to participate any more.
Do we have an automatic transfer of authorship to current authorship. Do we reserve right for the editors to allow a transfer to a different author if original authors are uncontactable. If we do this, we need to resolve issues about copyright of the remaining authors. 

If there are NO authors that want to participate, the article can just be retired.  It's more complicated if there are multiple authors.  

Remember that we are asking for a permissive license, ideally something like CC-BY, which may simplify some of these answers somewhat.

Do we need to maintain list of canonical repositories? Encourage all authors to fork so all authors have a copy.  We car fork the repo that’s published. We  fork your repository, automatically go into zenoo with DOI.  Get a separate DOI than the paper itself.

**Comment by davidlmobley** [comment]
I can take a stab at drafting something on this.

**Comment by mrshirts** [comment]
Started to elaborate this in https://github.com/livecomsjournal/journal_information/pull/25.

**Comment by davidlmobley** [comment]
This was resolved; at least, we now have a draft such policy up.
