### ISSUE TITLE
Allow mechanism for endorsements or signatories?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#23]
Do we want to have a mechanism for people to endorse a paper? How would a mechanism for endorsement work?  A section in the template?  How would people indicate? A comment in GitHub?  Is there a dispute mechanism for endorsement?  Could we have a problem of too many endorsees, when we really only want to have the most relevant people?

**Comment by davidlmobley** [comment]
I think just a section in addition to "Acknowledgments" which would be "Endorsers". I don't think too many would be a problem other than that the list might become cumbersome; obviously the most improtant people to have there will be the "well known researcher" type people. Presumably this would be coordinated by the authors and could be various mechanisms.

Dispute mechanism? I don't think there would need to be a formal one. If someone's name showed up by mistake they can sort it out with the authors.

**Comment by davidlmobley** [comment]
@dmzuckerman - should we have a template section for "endorsers", probably for best practices documents mainly?

**Comment by dmzuckerman** [comment]
how would this work?  if it requires a new pdf and article version for each endorser that may messy.  it also might be good to have it clear from the website who endorses ... did we decide there's no way to that?  or maybe it's better to keep it self-contained in the pdf anyway.  tricky.  also, how would we ensure the endorsement was official?  not clear this should be left to authors.  and what if the doc changes, do the endorsers have to confirm?  sorry if we already went over these issues.
________________________________

**Comment by davidlmobley** [comment]
> how would this work?  if it requires a new pdf and article version for each endorser that may messy.  it also might be good to have it clear from the website who endorses

I think the thought would be that people would update their GitHub repo (PDF and, if desired, README.md) with a list of endorsers as people endorse. This would typically happen after publication, presumably, and would be a "minor edit" so would not result in changes to the "published" version of the article, it'd just be a change to the latest version kept in the GitHub repo. When they publish a new version for other reasons, it would carry along with it a list of endorsers. 

> also, how would we ensure the endorsement was official?

Well, we could ask that the endorsers explicitly affirm it in a GitHub thread, maybe?  We could say, "Authors wishing to have a list of endorsers in their article should have a GitHub issue entitled, 'Comment here to endorse this article'" and commenters become endorsers, so it would be easy for us to check. See also below. 

>  and what if the doc changes, do the endorsers have to confirm?  sorry if we already went over these issues.

That is a good question. We could address this in the same way as the above -- anytime a new version is being released, a notification is posted in the "Comment here to endorse this article" thread, which triggers a GitHub notification to all the people who have commented in that thread, giving endorsers an opportunity to opt out. We could make this a matter of policy.

On the other hand, maybe this is too complex and we should just stick with something more normal. I don't see a huge advantage to having a list of endorsers, and it's just another thing to have to maintain.

**Comment by dmzuckerman** [comment]
Does Scholastica provide the ability to list citing papers?  If so, that could be implicit endorsement and that would be simple to do.  In the long term, perhaps there's some external badging/endorsement site we can link to later when we're a big time operation.
________________________________

**Comment by davidlmobley** [comment]
I think we can safely put this on hold for now and revisit if someone wants this. It's not a priority, I don't think.

**Comment by davidlmobley** [comment]
I think we just close this; it's just another layer of things to manage that I think won't be necessary. We can reopen later if it's something people want; marking as closed for now.
