### ISSUE TITLE
Feedback other than GitHub?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#24]
Will we have a feedback mechanism other than GitHub ever?

**Comment by davidlmobley** [comment]
Presumably people could contact the authors directly. Did you have something else in mind?

**Comment by justinGilmer** [comment]
I feel like submitting GitHub issues, or contacting the authors directly would be an excellent way to handle these. It gently forces them to collaborate and contribute to the articles in a pretty easy way. We will just need to make it very apparent how to find the source of the article and directly link to the issues section for each repository.

Possibly make it clear that this is not only an issues section, but for general feedback.
