### ISSUE TITLE
Privacy policy?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#26]
We probably need one, if we are taking information in for articles.  We need to check with scholasticahq.com for what information THEY collect for metrics, and what we need to do make sure we are keeping people happy with their privacy polcy.

**Comment by davidlmobley** [comment]
We concluded [here](https://github.com/livecomsjournal/livecomsjournal.github.io/issues/66#issuecomment-336336901) that no privacy policy is needed since it's covered by GitHub and Scholastica which are where their submissions actually are handled.
