### ISSUE TITLE
Find and install a markdown theme that meets requirements

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#34]
* Looks more like http://journals.plos.org/plosone/s/submission-guidelines
* not too visually jarringly different from http://www.livecomsjournal.org/

Will start with an existing one, then see if we need more development (will figure out WHO will do the development after).

**Comment by ptmerz** [comment]
I think the requirements can be reformulated to
1. has a header area (both livecomsjournal and plos have one)
2. has a sidebar navigation (as in the plos example above - allows to navigate long documents)
3. can be made to look similar to www.livecomsjournal.org

Github pages has a small number of integrated themes: https://pages.github.com/themes/. Of those, "Leap day" (https://pages-themes.github.io/leap-day/) seems to be the only one fulfilling requirements 1. & 2. (all others have _either_ a sidebar or a header area), but it is very far from looking similar to www.livecomsjournal.org.

Then, there are thousands of additional themes available online (paid and free ones, with very different licenses...), which, if I understood everything correctly, can be deployed on github pages by adding the files to the repo. Looking around for a while, I stumbled upon https://mmistakes.github.io/minimal-mistakes/, which looks like a good start. It has two columns, one of which can be used for navigation, it has a header area, it's customizable and visually not too far from livecomsjournal.org to start with, and it's licensed under MIT (we can do whatever we want with it, as long as we don't hold the original author reliable...). The github README (https://github.com/mmistakes/minimal-mistakes) has some screen shots, and https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/ is an example of a page with navigation.

If that looks like a good option, I can go ahead and (try to) adapt the current page to use this theme and create a pull request. It seems doable, but will likely take me a bit of time, so I'd be happy to have some opinions before I get started.

**Comment by ptmerz** [comment]
Oh, and one more thing - the PLOS example (http://journals.plos.org/plosone/s/submission-guidelines) has a dynamic sidebar that opens and closes submenus as you scroll. I don't think this is possible using jekyll and github-pages (which does not allow plugins), at least I didn't find anything like that. So the sidebar navigation would likely be static.

**Comment by davidlmobley** [comment]
@ptmerz - Minimal Mistakes looks awesome to me, seems like exactly what we need. Let's do it! 

> the PLOS example (http://journals.plos.org/plosone/s/submission-guidelines) has a dynamic sidebar that opens and closes submenus as you scroll. I don't think this is possible using jekyll and github-pages 

That's kind of what I figured -- it's "bells and whistles" and, while it looks cool, isn't functionally that important and I figured it would be beyond what we could easily (or at all) achieve here. So I'm fine with that. :)

**Comment by jchodera** [comment]
This sounds like a great improvement, @ptmerz!

It does look like both [collapsible](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_sidebar_navigation.html) and [dynamic](https://github.com/DigitalMindCH/docster-jekyll-theme) side navigation is possible in Jekyll, from what I've observed.

**Comment by jchodera** [comment]
Oh, but not necessarily `github-pages`, as you note above. Sorry!

**Comment by ptmerz** [comment]
Great, thanks for the feedback @davidlmobley and @jchodera. I'll go ahead and adapt the current webpage!

**Comment by mrshirts** [comment]
I think depending on the license, we are fine with either paid or free.

**Comment by davidlmobley** [comment]
I think this is resolved now!
