### ISSUE TITLE
Guidelines on writing style, etc.

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#38]
Currently, we say nothing at all about writing style and editing. I think we ought to:
1) Update the "Preparation of your article" section (https://livecomsjournal.github.io/#preparation-of-your-article-for-submission)  to say a bit about writing style/editing. We can:
a) reference the ACS Style guide (with links) which provides rather good guidance; we can strongly encourage authors to follow ACS style
b) note that we are not going to be editing the article in detail, so the authors should arrange for their own editing
2) Update "Review criteria" to indicate that reviewers will also note whether the article is well edited; authors whose article follows an inconsistent style, uses poor grammar, or is poorly edited may be asked to revise to address these issues before acceptance.

Does this sound reasonable, @mrshirts , @dmzuckerman ? If so I can add this.

**Comment by mrshirts** [comment]
This all sounds good.  IIRC, PLoS (http://journals.plos.org/plosone/s/submission-guidelines) has some language about copyediting being needed (under "Copyediting manuscripts "- we can use some of the ideas they have (w/o copying the text).  Frankly, if they have a section on something, we might consider it as well.

**Comment by davidlmobley** [comment]
Thanks, that's helpful. I'll get to this soon. Other things I should insert at the same time:
- Guidance as to layout: Point out to authors to take some care how their PDF looks as we are not typesetting it for them
- Suggest figures/tables be placed appropriately in the document, e.g. not at the end
- Numbered in order in which they are referenced in text
- Use consistent (and legible, not too small) font sizes in figures, etc.

@mrshirts - do you know what font the template uses? We could recommend that figures/images use this font too. :)

**Comment by mrshirts** [comment]
I THINK it's Open Sans (https://fonts.google.com/specimen/Open+Sans).   The LaTeX is:

   \setmainfont[Ligatures = TeX,
     Extension = .ttf,
     UprightFont = *-Regular,
     BoldFont = *-Bold,
     ItalicFont = *-Italic,
     BoldItalicFont = *-BoldItalic]
     {OpenSans}

**Comment by davidlmobley** [comment]
Resolved via #50
