### ISSUE TITLE
Make molecular images for scholastica and github pages

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#41]
Instead of the landscape backgrounds we currently use, we should probably use something stylish but molecular (alchemistry-ish, maybe, even?) that is pretty but also evokes the science we cover. Ideas?

**Comment by dmzuckerman** [comment]
a standard close-up of a ligand binding site might be good enough for short term.
________________________________

**Comment by mrshirts** [comment]
It might be worth getting an artist who does molecular visualization to generate a few images that can be used in the graphical identity.

**Comment by davidlmobley** [comment]
Should I look for one, @mrshirts , or do you have one in mind?

**Comment by mrshirts** [comment]
I haven't actually found one -- if you know of one or had a chance to look, that would be great.

**Comment by mrshirts** [comment]
We are talking to Merry Wang at Autodesk who will try to generate a few.

**Comment by ptmerz** [comment]
First draft included in github pages via pull request #69.

**Comment by davidlmobley** [comment]
Thanks!
