### ISSUE TITLE
Contact info? Update editors page with that info before opening for submissions

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#47]
@mrshirts - right now the instructions for presubmission letters say they should contact the lead editor in the relevant area but we have no contact info for these. Is the thought that we would be using dedicated e-mail addresses for these and post the contact info?

**Comment by mrshirts** [comment]
Yes, correct.  Since we don't have G-suites set up, we can just use our own emails for now?  Or just use the main email on Gmail until we have them. It's probably not that relevant until we open for submissions.

**Comment by davidlmobley** [comment]
Right now the link goes to the editorial board page on the main journal website, saying to contact the editor in the relevant area, but there is no contact info there. So we will need to update this before we open for submissions.

**Comment by davidlmobley** [comment]
Resolved recently.
