### ISSUE TITLE
Ask for representative image?

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#51]
PLoS asks authors for a "striking image" to represent their article on the home page; since we'll also have a single image that links to our articles, should we explicitly require one in our author guidelines? @mrshirts @dmzuckerman ?

**Comment by dmzuckerman** [comment]
given our sober ambitions, perhaps we should say 'representative' as you suggest.  but i think an image will help
________________________________

**Comment by mrshirts** [comment]
Scholastica actually requires that an image be submitted, so yes, we want that in the general policies.

**Comment by davidlmobley** [comment]
Added in #49
