### ISSUE TITLE
Clarification for "Best Practices" policies - "these issues"

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/livecomsjournal.github.io#57]
I'm not sure who wrote the first draft of the "Best Practices" policies document, but am hoping the author pops up.

One paragraph begins with:
"One can divide the types of errors that are made performing molecular simulations into (a) mistakes experienced researchers often make, and (b) mistakes new users often make, even after having received solid training in fundamentals of molecular simulation. Most checklists will be focused on these types of failures."

Which of "... these types of failures" is the document referring to? It could mean either the experienced users or new users, but I think the authors' intent was to refer to the new users. If anyone can clarify the original intent, please do. It needs a revision regardless, but I'd like to keep the original authors' intent.

**Comment by davidlmobley** [comment]
This is from @mrshirts . I think he means "both of these types of failures", i.e. things that experts make because they forget them (even though they know better) AND things newer users mess up because they don't know or because they forget them too.

**Comment by davidlmobley** [comment]
@mrshirts -- care to comment on this so we can finalize text?

**Comment by mrshirts** [comment]
It's not a great paragraph.  I think it could even be excised, or changed to "and (c), errors made without much training at all" and say we focus on (a) and (b).  Or say in place "we will focus more on errors that can still easily be made by people will some simulation savvy, rather than being a complete checklist of absolutely all things that can go wrong.

**Comment by dwsideriusNIST** [comment]
Thanks for the clarification Michael. I'll revise that paragraph, more from scratch.

**Comment by davidlmobley** [comment]
Closed by #72
