### ISSUE TITLE
Editorial Board on website not up to date

### ISSUE THREAD

**Issue by dmzuckerman** [livecomsjournal/livecomsjournal.github.io#63]
New editors have not been added and I think some lead editor info was actually deleted from a prior version.

**Comment by davidlmobley** [comment]
This actually belongs on the website repo; this is the one for teh GitHub Pages site. (It's confusing, ugh.) I'll create an issue.

**Comment by davidlmobley** [comment]
(Marking as closed here so we can deal with it over there).
