### ISSUE TITLE
Get legal advice on outstanding issues from CU, post responses here

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#66]
- [x] Privacy policy for the website
 - [x] Waiver saying that people giving us stuff have the right to do so (i.e. not encumbered by other people's IP)
 - [x] instructions for figure/text reuse.  We need language/info for authors to do this easily. Might be complicated depending on how specific it needs to be for other journals. 
 - [x] suggestions for policies for how to run a board of editors. 

 - [x] Have the lawyer include text that of the authors wish to change the license at some point in the future (e.g. from CC-BY 4.0 to a future CC-BY 5.0), this requires the consent of all authors. By procuring consent from all authors that future authors may change the license to a future version of the same license (or maybe another OSI-approved license) at the time of their contributions, this process can be made much easier. Many open source projects, for example, require authors to agree to this before their PRs are accepted.

 - [x] Have lawyer include text that people must agree to allow the article to move on after they leave the author group (see text in policies for abandoned articles for getting the wording right)

I will ask when we have compiled the issues.

**Comment by davidlmobley** [comment]
More explicit information for authors on what they should do in cases where their material is subject to an outside copyright agreement, e.g. such as in the case of Annual Reviews (as we use this as an example). 

I would *like* to be able to recruit people who have recently written for Annual Reviews to submit updated versions of their articles here as "perpetual reviews", but I would not want to do this without being able to give them legal advice as to handling of the copyright agreement. In the specific case of Annual Reviews, the authors retain the right to create (and potentially republish) derivative works as long as these works retain certain disclaimers and notifications (I can get you the exact requirements if you like, @mrshirts ). But, we have to sort out what exactly those would look like in our case, and what license we would recommend they use. So I think that leads to three things:
- [ ] What license should authors use if they are republishing derivative works created from Annual Reviews articles
- [ ] What precise disclaimers/information does their article need to contain to indicate the connections to Annual Reviews? (It is clear as long as it is the same work, but if it is a derivative work, how do they indicate that PORTIONS of the article are copyright Annual Reviews and portions are not?)
- [ ] What specific instructions should we give to authors to handle this scenario as well as more general versions of it (e.g. for materials under some other copyright agreement that gives them perhaps similar rights but with which we're not familiar)?

**Comment by mrshirts** [comment]
Thanks David!  Please link the exact requirements if you can.

**Comment by davidlmobley** [comment]
@mrshirts - here is a copy of the exact details from Annual Reviews. I am not aware if this exists on their website; it was e-mailed to me.

[AR.pdf](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1350687/AR.pdf)

**Comment by mrshirts** [comment]
Hmm.  It says here "The nonexclusive right to use, reproduce, distribute, perform, update, create derivatives, and make copies of the work (electronically or in print) in connection with the author’s teaching, conference presentations, lectures, and publications, provided the copies are not offered for sale and proper attribution is given".  Certainly it would need at least CC-BY-NC (attribution / noncommerical) would be OK, since it's not for sale.  But it looks like it only gives the AUTHOR the rights, which would mean that submitting the article to livecoms is fine (and having it published there), but that nothing could be done with the article by other people.   We might want to follow up with them a bit more if possible.

**Comment by mrshirts** [comment]
Note: I need to ask scholastica their privacy policy. It doesn't show up on www.livecomsjournal.org.

**Comment by davidlmobley** [comment]
I'm not sure, @mrshirts if that is the best route or if it is to talk to a lawyer first. I don't think AR is going to have much incentive to cooperate with us unless we have an author who is considering submitting to AR who has concerns, so it would probably be good to know exactly what rights authors have under these terms and what exactly we want from AR (from a lawyer) before we ask I think. Unless an author comes forward who has concerns with AR policies so we have a reason for dialog.

**Comment by mrshirts** [comment]
Note Scholastica's privacy policy is 
https://scholasticahq.com/privacy-policy
and GitHub's is 
https://help.github.com/articles/github-privacy-statement/
I'm not sure how these propagate over into our websites hosted with them.

**Comment by davidlmobley** [comment]
Michael, do we still need this issue open now that you've asked?

**Comment by mrshirts** [comment]
I want to keep it here for now, but I will add the documentation. When we have answers. 

For privacy policy, it appears that we rely on the GitHub and Scholastica sites, because they are the hosts.

For the other points, I think we are still waiting.

**Comment by mrshirts** [comment]
PR #126 addressed most of these issues by posting a copyright license letter that includes the points checked above. We are emailing Annual Reviews to get advice on what stance they will have on publishing an update of an AR paper.

We probably can't provide explicit text for now about including previous figures/text from other papers that covers all cases.

We are running the bylaws by the CU lawyers.

**Comment by mrshirts** [comment]
Bylaws now run by CU lawyers, they are fine with them other than a couple of suggestions put in PR #135

**Comment by mrshirts** [comment]
Right now, punted the last point (instructions for figure/text reuse) to just say that people are reminded they need to be responsible for getting permission to reuse things (in PR #182)
