### ISSUE TITLE
Some links are not clickable

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#73]
When mousing over the "Author Instructions" and "Editorial Policies" headers on the main page, they get underlined as if they are links (they appear active) but clicking them does nothing. This needs fixing since I repeatedly click them and wait for them to load (even though I know better by now!) and nothing happens. @ptmerz , any ideas?

(cc @bmanubay as this is also true for the openforcefield.org pages)

Here are the headers I'm talking about: 
![living_journal_of_computational_molecular_science_livecoms](https://user-images.githubusercontent.com/7132257/31521015-cf9cacba-af5c-11e7-846a-367a844f7c4f.jpg)

**Comment by bmanubay** [comment]
So, that uses the `splash` layout (which is mostly pieced together from `page.scss`). I think it would be a matter of editing something in how the splash page is pieced together (maybe?).

I'd have to look into it a little more.

**Comment by mrshirts** [comment]
This is for LiveCoMS, so perhaps @ptmerz  can chime in?

**Comment by ptmerz** [comment]
It's a "feature" of the theme, but luckily easy enough to change. See PR #74.

**Comment by davidlmobley** [comment]
Thanks.
