### ISSUE TITLE
Links for article types broken?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#80]
https://livecomsjournal.github.io/authors/policies/

The links to article type, of form - [Best Practices Guides](/best_practices/), appear broken.  Because of the complicated nature of the links, I'm not sure I want to mess around with how it's set up.

**Comment by mrshirts** [comment]
No, that didn't fix it.  Now the links are things like: https://livecomsjournal.github.io/authors/policies/authors/best_practices/, which is clearly not right.  Maybe @ptmerz l can take a look?

**Comment by ptmerz** [comment]
@davidlmobley Did PR #84 solve this also on your side? Seems to work for @mrshirts and me.

**Comment by davidlmobley** [comment]
Works now, yes, thanks.
