### ISSUE TITLE
What info do editors send to reviewers when requesting reviews?

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#91]
As preparing instructions for editors ( #90 ) I realized that the editors handling manuscripts will need to send a form letter (or, a custom letter based on a form letter) to potential reviewers to request reviews. This means we need to write the content for this. What should we include @mrshirts @dmzuckerman @hmayes ? Here's what I came up with so far:
- Brief explanation of what LiveCoMS is, with links
- Request to review with opt-in/opt-out links
- Link to COI policy for reviewers, with instructions to report potential conflicts
- Link to review criteria/author guidelines for particular category of articles
- Note possibility of providing non-anonymous feedback directly on GitHub repo (publicly) if they desire, e.g. if they like the article and want the authors to know who is providing the feedback

Should we also have a PAGE with reviewer instructions that this would link to?

**Comment by dmzuckerman** [comment]
This seems like the right list, along with the deadline.

In the interest of transparency, the (same) review criteria should be visible to authors and reviewers ... but it would be nice if reviewers had all the criteria in one place.  Perhaps that one place should be the letter, which could include as an 'appendix' (below signature) ... "For your convenience, we have gathered both the general [link] and category-specific [link] review criteria here:"

**Comment by davidlmobley** [comment]
That sounds like a good plan, yes.

**Comment by davidlmobley** [comment]
Assigned this to myself, though if someone else wants to, feel free.

**Comment by dmzuckerman** [comment]
I drafted two letters - one to inquire and one to thank ...

Dear XX,

We invite you to review the article indicated below, which has been submitted to the “YYY” category of the Living Journal of Computational Molecular Science (LiveCoMS).  LiveCoMS is a brand new and rather unique journal, which focuses on promoting best practices in molecular computation via updateable educational articles of various kinds - tutorials, reviews, best-practices “manuals” and “lessons learned” articles.  The journal is low-cost, non-profit and run by members of our community in a transparent way; in part, it aims to provide academic credit for important work that often goes unrewarded.  One unique feature of the review process is the requirement for a student review of every article.

Title:
Abstract:

To ACCEPT: link
To DECLINE: link

Reviews are generally expected within 10 days, although extra time may be allowable upon request.

If you have any questions, please reply to this email.  Our conflict-of-interest policies [link] should be understood by all reviewers.

Thank you very much.
QQQ, Associate Editor

Dear XX,

Thank you very much for agreeing to review the LiveCoMS submission, “ZZZ”.  Your support of our new community-run journal is very encouraging.

I would appreciate receiving your review within 10 days, by TTTTTT.

The article is to be considered under the YYY category.  To aid you in your review, both the general review criteria [link] and the criteria specific to category YYY [link] are appended below.

Please read our conflict-of-interest criteria and inform me of any potential conflicts.

Note also that non-anonymous feedback can be provided directly to authors via the github page linked in the manuscript.

If you have any questions, please reply to this email.

Thank you very much.
QQQ, Associate Editor

REVIEW CRITERIA
General
Category-specific

**Comment by davidlmobley** [comment]
This looks like a good start to me. Do you want to put them up in the repo somewhere so it's under version control (as a markdown file)? Probably we could put them up for now as one which won't be linked from the website (which you I think can do just by dumping the files here).

@mrshirts - how do things go on the Scholastica site? Do we have places to dump the templates for letters? Maybe you can provide a full list of templates we need?

**Comment by mrshirts** [comment]
> @mrshirts - how do things go on the Scholastica site?

Currently only one person can have permission to manage the scholastica site.

> Do we have places to dump the templates for letters? Maybe you can provide a full list of templates we need?

Yes, there are places to do it, however, it will be harder to see for edits, so we definitely should edit here first.  We plan on being open!

The templates/forms that are available are:

* Reviewer form. I have attached the current one.   Note the first section is required, we can edit or change all of the other questions.
[Living Journal of Computational Molecular Science Review Form.pdf](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1497918/Living.Journal.of.Computational.Molecular.Science.Review.Form.pdf)

* There's a decision letter template ( we can have up to 10). Merge tags are:
{{AUTHOR-FULL-NAME}}
{{AUTHOR-FIRST-NAME}}
{{AUTHOR-LAST-NAME}}
{{SENDER-FULL-NAME}}
{{SENDER-FIRST-NAME}}
{{SENDER-LAST-NAME}}
{{MANUSCRIPT-TITLE}}

* There's a reviewer letter template (We can have up to 10).   Merge tags are: 
{{SENDER-FULL-NAME}}
{{SENDER-FIRST-NAME}}
{{SENDER-LAST-NAME}}
{{MANUSCRIPT-TITLE}}

* There are editor invitation templates, but I don't know we need the.

**Comment by davidlmobley** [comment]
@mrshirts - there's no option to have a merge tag for abstract in the reviewer letter?

**Comment by mrshirts** [comment]
Abstract is automatically included.

**Comment by davidlmobley** [comment]
Would be resolved by #108.

**Comment by davidlmobley** [comment]
Resolved by #108 .
