### ISSUE TITLE
Super rough draft text for "call for submissions" press release

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#93]
I'm trying to draft up a call for submissions for use at our "soft opening" in December (when we open for submissions). Since I need feedback on this anyway I'll the draft CONTENT it in a branch on this repo to allow people to edit (or just comment in this thread). Ultimately I'll format this nicely as an image or something similar for posting, tweeting, etc., but first comes the content.

View the content draft [here](https://github.com/livecomsjournal/livecomsjournal.github.io/blob/press/call_for_submissions.md) (link https://github.com/livecomsjournal/livecomsjournal.github.io/blob/press/call_for_submissions.md)

**Comment by davidlmobley** [comment]
@mrshirts @dmzuckerman - this should be listing Section Lead e-mail addresses for people to contact with a presubmission inquiry. Do we have those in place now? Or a single e-mail address for all leads?

**Comment by mrshirts** [comment]
We have them, I need to configure.

**Comment by davidlmobley** [comment]
OK. Can I get the addresses to put in the press release? Or, if it will take a while, should I just use our personal addresses for now?
Thanks.

David Mobley 949-385-2436 (cell)
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.79&pv=10.13.1&source=email_footer_2]
On Wed, Nov 15, 2017 at 2:15 PM, Michael Shirts <notifications@github.com> wrote:
We have them, I need to configure.

**Comment by davidlmobley** [comment]
PR is drafted and waiting for Dec. 1 to advertise. Closing.
